services:
  - type: web
    name: langjiayuan-jujube-monitoring
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        value: sqlite:///agriculture.db
      - key: SECRET_KEY
        generateValue: true 